#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -pe omp 16
#
source /etc/bashrc

module load gcc 

GENOMEDIR=/projectnb2/bf528/project_3/reference/rn4_STAR/

# STAR 2.5.3a isn't available in module load, and conda was giving me grief
# so I just built it from source
/usr4/bf528/tfalk/STAR-2.5.3a/source/STAR \
  --readFilesIn /projectnb2/bf528/project_3/samples/${1}_1.fastq.gz \
  /projectnb2/bf528/project_3/samples/${1}_2.fastq.gz \
  --genomeDir $GENOMEDIR \
  --runThreadN 16 \
  --readFilesCommand zcat \
  --outSAMtype BAM SortedByCoordinate \
  --outFilterType BySJout \
  --outFilterMultimapNmax 20 \
  --alignSJoverhangMin 8 \
  --alignSJDBoverhangMin 1 \
  --outFilterMismatchNmax 999 \
  --alignIntronMin 20 \
  --alignIntronMax 1000000 \
  --alignMatesGapMax 1000000 \
  --outFileNamePrefix $1
  

